### ISSUE TITLE
search results are wrong?

### ISSUE THREAD

**Issue by cnut1648** [haydenull/logseq-plugin-file-manager#3]
Hi, thank you for the plugin!

I have a question, it seems that the search results are not accurate.
For example, here it finds `000all_1646111183620_0.gif`
![image](https://user-images.githubusercontent.com/37067883/164560594-f31f47d2-09fd-4563-a87f-e4a3d3ecc690.png)

but this gif does appear in my note
![image](https://user-images.githubusercontent.com/37067883/164560560-f8543ca1-de86-4d5b-87f3-dd9a569473df.png)

I am wondering what can be wrong here. Thanks!

**Comment by haydenull** [comment]
May I know the markdown file path? The plugin currently only detects files under `journals` `pages` `logseq/bak/journals` `logseq/bak/pages`.

**Comment by cnut1648** [comment]
@haydenull Hi, I guess this might be the issue, The markdown is in the path `pages/OKR/2022`. Does the plugin currently support the subdirectory?

**Comment by haydenull** [comment]
Yes, version 1.3.0 supports subfolders of pages. You can try again.

**Comment by cnut1648** [comment]
@haydenull Thanks!! That solves it.
